import type { NextPage } from "next";
import Head from "next/head";
import {
  About,
  ContactMe,
  Experience,
  Header,
  Hero,
  Project,
  Skills,
} from "../components";
const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Milan portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id="hero" className="snap-center">
        <Hero />
      </section>

      <section id="about" className="snap-center">
        <About />
      </section>

      <section id="experiance" className="snap-center">
        <Experience />
      </section>

      <section id="experiance" className="snap-center">
        <Skills />
      </section>

      <section id="project" className="snap-center">
        <Project />
      </section>

      {/* Contact me */}
      <ContactMe />
    </div>
  );
};

export default Home;
